config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :reminders

  root 'home#index'
  get 'reminder' => 'reminders#new'

  get "/auth/:provider/callback/" => "authentication#create"
  get "/auth/:provider/" => "authentication#create", :as => :login
  get "/signout" => "authentication#destroy", :as => :signout

  get 'dashboard/:id' => 'dashboard#show', :as => :dashboard

  post 'twilio/voice/:id' => 'twilio#voice'

  patch 'dashboard/:id/update_user_phone' => 'dashboard#update_user_phone'

  get 'admin' => 'admin#login'
  post 'admin' => 'admin#authenticate'
  get '/admin/panel' => 'admin#index'

  post 'mass_message' => 'reminders#mass_message'

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  validates :message, :phone, presence: true
  validates :phone, numericality: true, length: { minimum: 7 }


  belongs_to :user

  def self.check_reminders
    active = Reminder.where(active: :true)

    if active.count < 1
      puts "No Reminders To Be Sent"
    else
      #check active records and if the reminder time has elapsed,
      #send the twilio message and mark the reminder as inactive
      active.each do |reminder|
        if reminder.reminder_time < Time.now
          generate_reminder(reminder)
          reminder.active = false
          reminder.save
        end
      end
    end


  end

  #takes reminder object and sends message based on its parameters
  def self.generate_reminder(reminder)
    account_sid = ENV['ACCOUNT_SID']
    auth_token = ENV['AUTH_TOKEN']
    #binding.pry

    if reminder.sms == true
      # set up a client to talk to the Twilio REST API
      @client = Twilio::REST::Client.new account_sid, auth_token

      @client.account.messages.create({
                                        :from => '+19787889381',
                                        :to => reminder.phone,
                                        :body => 'Remio Service Reminder: ' << reminder.message
      })
    end

    #send a phone notification if reminder has phone call notification
    if reminder.call == true
      #binding.pry
      # set up a client to talk to the Twilio REST API
      @client = Twilio::REST::Client.new account_sid, auth_token

      #use different url for testing and production
      if Rails.env.development?
        #setup custom xml document for notification - TBD
        @call = @client.account.calls.create({
                                               :url => 'http://b7b6c37.ngrok.com/twilio/voice/' << reminder.id.to_s,
                                               :from => '+19787889381',
                                               :to =>  reminder.phone,
                                               :IfMachine => 'Continue'
        })

      else
        #setup custom xml document for notification - TBD
        @call = @client.account.calls.create({
                                               :url => 'http://futuretide.net/twilio/voice/' << reminder.id.to_s,
                                               :from => '+19787889381',
                                               :to =>  reminder.phone,
                                               :IfMachine => 'Continue'
        })
      end

    end

  end

  #mass message stub
  def self.mass_message(message)
    message
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /reminders
  # GET /reminders.json
  def index
    admin?
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  #mass message
  #sends an immediate reminder out to the list of numbers
  def mass_message
    #binding.pry
    #take numbers and split up into array
    numbers = params[:mass_message][:numbers]

    #contains_invalid_chars = numbers =~ /\D/

    # binding.pry
    numbers = numbers.split

    #check if there are actual numbers to send the message to
    #if not, return error message
    if numbers.count > 0

      #restrict amount of messages to be sent to a total of 5
      if numbers.count > 5
        redirect_to dashboard_path(current_user.id), notice: 'Maximum of 5 numbers allowed for mass messages.' and return
      end

      #get message
      message = params[:mass_message][:message]

      #binding.pry

      date_time = Time.new(params[:date]["year"].to_i, params[:date]["month"].to_i,
                           params[:date]["day"].to_i, params[:date]["hour"].to_i,
                           params[:date]["minute"].to_i)
     
      #send message to each number
      numbers.each do |number|
        reminder = Reminder.create(message: message, phone: number, reminder_time:  date_time,
                                   user_id: current_user.id, sms: true)

        #check validation of numbers before sending
        #Note: wills save reminders successfully until an error has been found
        if reminder.save
          #continue
        else
          redirect_to dashboard_path(current_user.id), notice: 'Please only include valid numbers with no special characters.' and return
        end
      end

      #return success message
      redirect_to dashboard_path(current_user.id), notice: 'Mass message reminder submitted successfuly.'
    else
      #return error message
      redirect_to dashboard_path(current_user.id), notice: 'You must include at least one number for a mass message.'
    end

  end


  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        #Reminder.generate_reminder(@reminder)
        format.html { redirect_to dashboard_path(current_user.id), notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { redirect_to dashboard_path(current_user.id), notice: 'All fields must be filled out correctly' }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      if current_user.admin == true
        format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to dashboard_path(current_user.id), notice: 'Reminder was successfully destroyed.' }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reminder_params
    params.require(:reminder).permit(:message, :reminder_time, :phone, :default, :user_id, :call, :sms)
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= bootstrap_form_for(@reminder, layout: :inline) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :message, id: 'message', maxlength: 160 %>
  </div>
  <div class="field">

    <%= f.datetime_select :reminder_time, ampm: true, default: Time.now %>
  </div>
  <% if current_user.admin == true %>
    <div class="field">

    <%= f.text_field :phone, control_col: "col-md-9" %>
  </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing reminder</h1>

<%= render 'form' %>

<% if session[:admin] == true %>
<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>
<% else %>
<%= link_to 'Back', dashboard_path(current_user.id) %>
<% end %>

app/views/reminders/index.html.erb
<h1>Listing reminders</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Reminder time</th>
      <th>Phone</th>
      <th>Active</th>
      <th>User</th>
      <th>Call</th>
      <th>SMS</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.message %></td>
        <td><%= reminder.reminder_time %></td>
        <td><%= reminder.phone %></td>
         <td><%= reminder.active %></td>
         <td><%= reminder.user_id %></td>
         <td><%= reminder.call %></td>
         <td><%= reminder.sms %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @reminder.message %>
</p>

<p>
  <strong>Reminder time:</strong>
  <%= @reminder.reminder_time %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reminder.phone %>
</p>

<% if session[:admin] == true %>
	<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
	<%= link_to 'Back', reminders_path %>
<% else %>
	<%= link_to 'Back', dashboard_path(current_user.id) %>
<% end %>