config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :reminders

  root 'home#index'
  get 'reminder' => 'reminders#new'

  get "/auth/:provider/callback/" => "authentication#create"
  get "/auth/:provider/" => "authentication#create", :as => :login
  get "/signout" => "authentication#destroy", :as => :signout

  get 'dashboard/:id' => 'dashboard#show', :as => :dashboard

  post 'twilio/voice/:id' => 'twilio#voice'

  patch 'dashboard/:id/update_user_phone' => 'dashboard#update_user_phone'

  get 'admin' => 'admin#login'
  post 'admin' => 'admin#authenticate'
  get '/admin/panel' => 'admin#index'

  post 'mass_message' => 'reminders#mass_message'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remio.me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://apis.google.com/js/client:platform.js" async defer></script>


</head>
<body>
<div id="wrap">

<div class="container">
      <div class="jumbotron">
        <h1>Remio</h1>
        <p>Remio will send you an SMS or voice message to remind you of important events or appointments.</p>	

      </div>
      <div>
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <% if current_user != nil %>
                <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
                <li><%= link_to "Sign in with Google", login_path("google_oauth2") %></li>
        <% end%>

        <li><%= link_to "About",'#', onclick:'alert("Remio is a minimalist service that will text or voice message you with a reminder at the time you schedule.")'  %></li>
      </ul>
    </div>
  </div>
</nav>
      </div>

      <div>
		   <%= yield %>
	    </div>
	  

      <div id="push"></div>

      <div id="footer">
      <div class="container">
      <div id="push">
        <p class="muted credit"><h4>&copy; 2015 Stephen Griffin</h4></p>
        </div>
      </div>
    </div>

</div>

</div>



</body>
</html>